# Generated by Django 5.1.1 on 2024-09-26 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="height",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, unique="profile/", upload_to=""
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="weight",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
