# Generated by Django 5.1.1 on 2024-09-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="goal",
            field=models.CharField(default="Default Goal", max_length=300),
        ),
        migrations.AddField(
            model_name="challenge",
            name="reward",
            field=models.CharField(default="No reward", max_length=200),
        ),
        migrations.AddField(
            model_name="challenge",
            name="tracking_method",
            field=models.TextField(default="Tracking method"),
        ),
    ]
