# Generated by Django 5.1.1 on 2024-09-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Challenges", "0002_challenge_goal_challenge_reward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="challenge_img",
            field=models.ImageField(blank=True, null=True, upload_to="challenges/"),
        ),
    ]
