# Generated by Django 5.1.1 on 2024-09-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Programm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programm_img", models.ImageField(upload_to="programm/")),
                ("programm_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=600)),
                ("key_features", models.CharField(max_length=200)),
                ("work_include", models.CharField(max_length=200)),
                ("example", models.CharField(max_length=200)),
            ],
        ),
    ]
